export const Users = [
  {
    id: 1,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956910/6_unb4d4.jpg",
    username: "Jane Foster",
  },
  {
    id: 2,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956910/3_xaaq8s.jpg",
    username: "Slade Wilson",
  },
  {
    id: 3,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956910/4_b9qyxc.jpg",
    username: "Aja Adanna",
  },
  {
    id: 4,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956909/1_juqok7.jpg",
    username: "Kitty Pryde",
  },
  {
    id: 5,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956909/2_obabl8.jpg",
    username: "Jean Grey",
  },
  {
    id: 6,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956910/5_de2uxc.jpg",
    username: "Wanda Maximoff",
  },
  {
    id: 7,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956913/7_x83krl.jpg",
    username: "T'Challa",
  },
  {
    id: 8,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956912/10_gpf2eh.jpg",
    username: "Natasha Romanoff",
  },
  {
    id: 9,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956909/2_obabl8.jpg",
    username: "Ororo Munroe",
  },
  {
    id: 10,
    profilePicture: "https://res.cloudinary.com/clean-codes/image/upload/v1632956910/5_de2uxc.jpg",
    username: "Harley Quinn",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/9_yv0cfp.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://res.cloudinary.com/clean-codes/image/upload/v1632957196/7_raoykj.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
